### ISSUE TITLE
HMR Typescript errors

### ISSUE THREAD

**Issue by sheilagithub** [Maarten88/rrod#3]
Hello - thanks for such a lovely tutorial!  I was attempting to run your solution and am receiving the following errors, do you know what I might be able to do to resolve?

[HMR] bundle has 8 errors
client.js:161 [at-loader] ./ClientApp/boot-client.tsx:24:6 
    TS2604: JSX element type 'Provider' does not have any construct or call signatures.
[at-loader] ./ClientApp/boot-server.tsx:45:18 
    TS2604: JSX element type 'Provider' does not have any construct or call signatures.
[at-loader] ./ClientApp/components/Home.tsx:10:13 
    TS2322: Type '{}' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<FullScreen> & { children?: ReactNode; } & void'.
  Type '{}' is not assignable to type 'void'.
[at-loader] ./ClientApp/store/Contact.ts:79:14 
    TS2322: Type '(state: ContactState, action: KnownAction) => ContactState' is not assignable to type 'Reducer<ContactState>'.
  Types of parameters 'action' and 'action' are incompatible.
    Type 'A' is not assignable to type 'KnownAction'.
      Type 'Action' is not assignable to type 'KnownAction'.
        Type 'Action' is not assignable to type 'SubmitContactFormAction'.
          Property 'payload' is missing in type 'Action'.
            Type 'A' is not assignable to type 'ContactFormErrorAction'.
              Type 'Action' is not assignable to type 'ContactFormErrorAction'.
                Property 'payload' is missing in type 'Action'.
[at-loader] ./ClientApp/store/Session.ts:53:14 
    TS2322: Type '(state: SettingsState, action: InitConfigAction) => SettingsState' is not assignable to type 'Reducer<SettingsState>'.
  Types of parameters 'action' and 'action' are incompatible.
    Type 'A' is not assignable to type 'InitConfigAction'.
      Type 'Action' is not assignable to type 'InitConfigAction'.
        Property 'payload' is missing in type 'Action'.
[at-loader] ./node_modules/@types/react-redux/index.d.ts:179:31 
    TS2314: Generic type 'Component<P, S>' requires 2 type argument(s).
[at-loader] ./node_modules/@types/react-router/lib/withRouter.d.ts:3:99 
    TS2314: Generic type 'PureComponent<P, S>' requires 2 type argument(s).
[at-loader] ./node_modules/@types/react/index.d.ts:165:11 
    TS2559: Type 'Component<P, S>' has no properties in common with type 'ComponentLifecycle<P, S>'.

**Comment by Maarten88** [comment]
Yes, as I wrote in my blog, modern javascript suffers from bit-rot, not doing maintenance will break any sourcecode after a few weeks.
In this case, two things happened:
- Typescript 2.4 came out, with stricter typechecking. This broke some Redux type checks in the store code.
- All React typings [were updated](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17288) in a way that was not backwards compatible 

The package.json specified versions with ^, meaning it automatically takes minor version updates, and these changes broke the code.

I pushed an [update](https://github.com/Maarten88/rrod/commit/6d2466da1ec60c76a49cdfa730fcb440513b06aa) that fixes typescript to version 2.3, and updates my react components to use the new definitions so everything builds again.

Let me know if this doesn't work for you.
