### ISSUE TITLE
instructions wasn't working

### ISSUE THREAD

**Issue by murugaratham** [Maarten88/rrod#8]
Great work first of all, but in your blog, you've mentioned to do 
```

dotnet restore
dotnet build
dotnet run
``` 
on the OrleansHost then webapp. I'm trying this out on a OSX with latest donet core 2.0.3. i skipped the dotnet run part, and instead used VS Code with launch `Launch & Debug All`, there's HotModuleReplacement errors, and realised that i need to run `npm i` on WebApp dir first to download the node modules before `npm run build:debug`

You've also mentioned that you chose dot net core as you wanted XPlat capabilities, but having ReduxTableStorage having a Azure Storage Emulator kinda defeats the purpose.

**Comment by Maarten88** [comment]
Thanks for reporting, I have updated the blog post to add the instruction.
